export const mockTripData = {
  id: "trip-1",
  title: "Hà Nội ➔ Singapore",
  durationDays: 4,
  totalBudget: 15000000,
  currentBudget: 12300000,
  destinations: ["Singapore"],
  days: [
    {
      id: "day-1",
      title: "Ngày 1",
      activities: [
        {
          id: "act-1",
          time: "09:00",
          title: "Changi Airport",
          description: "Đón xe, check-in khách sạn",
          cost: 0,
          lat: 1.3644,
          lng: 103.9915,
        },
        {
          id: "act-2",
          time: "13:00",
          title: "Hawker Centre",
          description: "Ăn trưa, thưởng thức ẩm thực địa phương",
          cost: 80000,
          lat: 1.2823,
          lng: 103.8448,
        },
        {
          id: "act-3",
          time: "15:00",
          title: "Gardens by the Bay",
          description: "Tham quan, chụp ảnh",
          cost: 0,
          lat: 1.2816,
          lng: 103.8636,
        },
        {
          id: "act-4",
          time: "19:00",
          title: "Marina Bay Sands",
          description: "Xem ánh đèn, dạo quanh",
          cost: 120000,
          lat: 1.2838,
          lng: 103.8591,
        },
      ],
    },
    {
      id: "day-2",
      title: "Ngày 2",
      activities: [
        {
          id: "act-5",
          time: "09:30",
          title: "Sentosa Island",
          description: "Vui chơi giải trí",
          cost: 1500000,
          lat: 1.2494,
          lng: 103.8303,
        },
        {
          id: "act-6",
          time: "14:00",
          title: "Universal Studios",
          description: "Chơi các trò chơi mạo hiểm",
          cost: 0,
          lat: 1.254,
          lng: 103.8238,
        },
        {
          id: "act-7",
          time: "19:30",
          title: "Clarke Quay",
          description: "Ăn tối và dạo quanh sông",
          cost: 200000,
          lat: 1.2893,
          lng: 103.8456,
        },
      ],
    },
  ],
}
